version: "3.8"

services:
  rpi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    container_name: rpi-jenkins-container
    volumes:
      - ./:/workspace
    environment:
      - TZ=UTC
    ports:
      - "9090:8080" # For Jenkins web interface (host:container)
    volumes:
      - jenkins_home:/var/jenkins_home
    devices:
      - "/dev/gpiomem:/dev/gpiomem" # For GPIO access
      - "/dev/i2c-1:/dev/i2c-1" # For I2C devices
    privileged: true # Required for full GPIO access
    restart: unless-stopped
    command: /usr/local/bin/jenkins-start.sh

networks:
  default:
    name: rpi-network

volumes:
  jenkins_home:
    driver: local
