header:
  version: 8

# filepath: /home/sandeshghimire/workspace/soc/mcp/repos/meta-security.yml
repos:
  meta-security:
    url: https://github.com/Xilinx/meta-security
    branch: rel-v2024.2
    path: sources/meta-security
    
